// <auto-generated />
namespace ShopSmart.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Places : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Places));
        
        string IMigrationMetadata.Id
        {
            get { return "201504231424091_Places"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
